// "https://media.api-sports.io/football/teams/33.png"
export const Teams = [
  {
    id: 33,
    name: "Man Utd",
    code: "MUN",
    country: "England",
    founded: 1878,
    national: false,
  },
  {
    id: 34,
    name: "Newcastle",
    code: "NEW",
    country: "England",
    founded: 1892,
    national: false,
  },
  {
    id: 35,
    name: "Bournemouth",
    code: "BOU",
    country: "England",
    founded: 1899,
    national: false,
  },
  {
    id: 36,
    name: "Fulham",
    code: "FUL",
    country: "England",
    founded: 1879,
    national: false,
  },
  {
    id: 39,
    name: "Wolves",
    code: "WOL",
    country: "England",
    founded: 1877,
    national: false,
  },
  {
    id: 40,
    name: "Liverpool",
    code: "LIV",
    country: "England",
    founded: 1892,
    national: false,
  },
  {
    id: 41,
    name: "Southampton",
    code: "SOU",
    country: "England",
    founded: 1885,
    national: false,
  },
  {
    id: 42,
    name: "Arsenal",
    code: "ARS",
    country: "England",
    founded: 1886,
    national: false,
  },
  {
    id: 45,
    name: "Everton",
    code: "EVE",
    country: "England",
    founded: 1878,
    national: false,
  },
  {
    id: 46,
    name: "Leicester",
    code: "LEI",
    country: "England",
    founded: 1884,
    national: false,
  },
  {
    id: 47,
    name: "Spurs",
    code: "TOT",
    country: "England",
    founded: 1882,
    national: false,
  },
  {
    id: 48,
    name: "West Ham",
    code: "WES",
    country: "England",
    founded: 1895,
    national: false,
  },
  {
    id: 49,
    name: "Chelsea",
    code: "CHE",
    country: "England",
    founded: 1905,
    national: false,
  },
  {
    id: 50,
    name: "Man City",
    code: "MAC",
    country: "England",
    founded: 1880,
    national: false,
  },
  {
    id: 51,
    name: "Brighton",
    code: "BRI",
    country: "England",
    founded: 1901,
    national: false,
  },
  {
    id: 52,
    name: "Crystal Palace",
    code: "CRY",
    country: "England",
    founded: 1905,
    national: false,
  },
  {
    id: 55,
    name: "Brentford",
    code: "BRE",
    country: "England",
    founded: 1889,
    national: false,
  },
  {
    id: 57,
    name: "Ipswich",
    code: "IPS",
    country: "England",
    founded: 1878,
    national: false,
  },
  {
    id: 65,
    name: "Nott\u0027m Forest",
    code: "NOT",
    country: "England",
    founded: 1865,
    national: false,
  },
  {
    id: 66,
    name: "Aston Villa",
    code: "AST",
    country: "England",
    founded: 1874,
    national: false,
  },
  // LALIGA

  {
    id: 529,
    name: "FC Barcelona",
    code: "BAR",
    country: "Spain",
    founded: 1899,
    national: false,
  },
  {
    id: 530,
    name: "Atlético de Madrid",
    code: "MAD",
    country: "Spain",
    founded: 1903,
    national: false,
  },
  {
    id: 531,
    name: "Athletic Club",
    code: "BIL",
    country: "Spain",
    founded: 1898,
    national: false,
  },
  {
    id: 532,
    name: "Valencia CF",
    code: "VAL",
    country: "Spain",
    founded: 1919,
    national: false,
  },
  {
    id: 533,
    name: "Villarreal CF",
    code: "VIL",
    country: "Spain",
    founded: 1923,
    national: false,
  },
  {
    id: 534,
    name: "UD Las Palmas",
    code: "PAL",
    country: "Spain",
    founded: 1949,
    national: false,
  },
  {
    id: 536,
    name: "Sevilla FC",
    code: "SEV",
    country: "Spain",
    founded: 1890,
    national: false,
  },
  {
    id: 537,
    name: "CD Leganés",
    code: "LEG",
    country: "Spain",
    founded: 1928,
    national: false,
  },
  {
    id: 538,
    name: "RC Celta",
    code: "CEL",
    country: "Spain",
    founded: 1923,
    national: false,
  },
  {
    id: 540,
    name: "RCD Espanyol de Barcelona",
    code: "ESP",
    country: "Spain",
    founded: 1900,
    national: false,
  },
  {
    id: 541,
    name: "Real Madrid",
    code: "REA",
    country: "Spain",
    founded: 1902,
    national: false,
  },
  {
    id: 542,
    name: "Deportivo Alavés",
    code: "ALA",
    country: "Spain",
    founded: 1921,
    national: false,
  },
  {
    id: 543,
    name: "Real Betis",
    code: "BET",
    country: "Spain",
    founded: 1907,
    national: false,
  },
  {
    id: 546,
    name: "Getafe CF",
    code: "GET",
    country: "Spain",
    founded: 1983,
    national: false,
  },
  {
    id: 547,
    name: "Girona FC",
    code: "GIR",
    country: "Spain",
    founded: 1930,
    national: false,
  },
  {
    id: 548,
    name: "Real Sociedad",
    code: "RSO",
    country: "Spain",
    founded: 1909,
    national: false,
  },
  {
    id: 720,
    name: "Real Valladolid CF",
    code: "VAL",
    country: "Spain",
    founded: 1928,
    national: false,
  },
  {
    id: 727,
    name: "CA Osasuna",
    code: "OSA",
    country: "Spain",
    founded: 1920,
    national: false,
  },
  {
    id: 728,
    name: "Rayo Vallecano",
    code: "RAY",
    country: "Spain",
    founded: 1924,
    national: false,
  },
  {
    id: 798,
    name: "RCD Mallorca",
    code: "MAL",
    country: "Spain",
    founded: 1916,
    national: false,
  },
  // SERIE A
  {
    id: 487,
    name: "Lazio",
    code: "LAZ",
    country: "Italy",
    founded: 1900,
    national: false,
  },
  {
    id: 489,
    name: "Milan",
    code: "MIL",
    country: "Italy",
    founded: 1899,
    national: false,
  },
  {
    id: 490,
    name: "Cagliari",
    code: "CAG",
    country: "Italy",
    founded: 1920,
    national: false,
  },
  {
    id: 492,
    name: "Napoli",
    code: "NAP",
    country: "Italy",
    founded: 1904,
    national: false,
  },
  {
    id: 494,
    name: "Udinese",
    code: "UDI",
    country: "Italy",
    founded: 1896,
    national: false,
  },
  {
    id: 495,
    name: "Genoa",
    code: "GEN",
    country: "Italy",
    founded: 1893,
    national: false,
  },
  {
    id: 496,
    name: "Juventus",
    code: "JUV",
    country: "Italy",
    founded: 1897,
    national: false,
  },
  {
    id: 497,
    name: "Roma",
    code: "ROM",
    country: "Italy",
    founded: 1927,
    national: false,
  },
  {
    id: 499,
    name: "Atalanta",
    code: "ATA",
    country: "Italy",
    founded: 1907,
    national: false,
  },
  {
    id: 500,
    name: "Bologna",
    code: "BOL",
    country: "Italy",
    founded: 1909,
    national: false,
  },
  {
    id: 502,
    name: "Fiorentina",
    code: "FIO",
    country: "Italy",
    founded: 1926,
    national: false,
  },
  {
    id: 503,
    name: "Torino",
    code: "TOR",
    country: "Italy",
    founded: 1906,
    national: false,
  },
  {
    id: 504,
    name: "Hellas Verona",
    code: "VER",
    country: "Italy",
    founded: 1903,
    national: false,
  },
  {
    id: 505,
    name: "Inter",
    code: "INT",
    country: "Italy",
    founded: 1908,
    national: false,
  },
  {
    id: 511,
    name: "Empoli",
    code: "EMP",
    country: "Italy",
    founded: 1920,
    national: false,
  },
  {
    id: 517,
    name: "Venezia",
    code: "VEN",
    country: "Italy",
    founded: 1907,
    national: false,
  },
  {
    id: 523,
    name: "Parma",
    code: "PAR",
    country: "Italy",
    founded: 1913,
    national: false,
  },
  {
    id: 867,
    name: "Lecce",
    code: "LEC",
    country: "Italy",
    founded: 1908,
    national: false,
  },
  {
    id: 895,
    name: "Como",
    code: "COM",
    country: "Italy",
    founded: 1907,
    national: false,
  },
  {
    id: 1579,
    name: "Monza",
    code: "MON",
    country: "Italy",
    founded: 1912,
    national: false,
  },
  // Bundesliga

  {
    id: 157,
    name: "FC Bayern München",
    code: "BAY",
    country: "Germany",
    founded: 1900,
    national: false,
  },
  {
    id: 160,
    name: "SC Freiburg",
    code: "FRE",
    country: "Germany",
    founded: 1904,
    national: false,
  },
  {
    id: 161,
    name: "VfL Wolfsburg",
    code: "WOL",
    country: "Germany",
    founded: 1945,
    national: false,
  },
  {
    id: 162,
    name: "SV Werder Bremen",
    code: "WER",
    country: "Germany",
    founded: 1899,
    national: false,
  },
  {
    id: 163,
    name: "Borussia Mönchengladbach",
    code: "MOE",
    country: "Germany",
    founded: 1900,
    national: false,
  },
  {
    id: 164,
    name: "1. FSV Mainz 05",
    code: "MAI",
    country: "Germany",
    founded: 1905,
    national: false,
  },
  {
    id: 165,
    name: "Borussia Dortmund",
    code: "DOR",
    country: "Germany",
    founded: 1909,
    national: false,
  },
  {
    id: 167,
    name: "TSG Hoffenheim",
    code: "HOF",
    country: "Germany",
    founded: 1899,
    national: false,
  },
  {
    id: 168,
    name: "Bayer 04 Leverkusen",
    code: "BAY",
    country: "Germany",
    founded: 1904,
    national: false,
  },
  {
    id: 169,
    name: "Eintracht Frankfurt",
    code: "EIN",
    country: "Germany",
    founded: 1899,
    national: false,
  },
  {
    id: 170,
    name: "FC Augsburg",
    code: "AUG",
    country: "Germany",
    founded: 1907,
    national: false,
  },
  {
    id: 172,
    name: "VfB Stuttgart",
    code: "STU",
    country: "Germany",
    founded: 1893,
    national: false,
  },
  {
    id: 173,
    name: "RB Leipzig",
    code: "LEI",
    country: "Germany",
    founded: 2009,
    national: false,
  },
  {
    id: 176,
    name: "VfL Bochum 1848",
    code: "BOC",
    country: "Germany",
    founded: 1848,
    national: false,
  },
  {
    id: 180,
    name: "1. FC Heidenheim 1846",
    code: "HEI",
    country: "Germany",
    founded: 1946,
    national: false,
  },
  {
    id: 182,
    name: "1. FC Union Berlin",
    code: "UNI",
    country: "Germany",
    founded: 1966,
    national: false,
  },
  {
    id: 186,
    name: "FC St. Pauli",
    code: "PAU",
    country: "Germany",
    founded: 1910,
    national: false,
  },
  {
    id: 191,
    name: "Holstein Kiel",
    code: "HOL",
    country: "Germany",
    founded: 1900,
    national: false,
  },
  // Ligue 1
  {
    id: 77,
    name: "Angers SCO",
    code: "ANG",
    country: "France",
    founded: 1919,
    national: false,
  },
  {
    id: 79,
    name: "LOSC Lille",
    code: "LIL",
    country: "France",
    founded: 1944,
    national: false,
  },
  {
    id: 80,
    name: "Olympique Lyonnais",
    code: "LYO",
    country: "France",
    founded: 1950,
    national: false,
  },
  {
    id: 81,
    name: "Olympique de Marseille",
    code: "MAR",
    country: "France",
    founded: 1899,
    national: false,
  },
  {
    id: 82,
    name: "Montpellier Hérault SC",
    code: "MON",
    country: "France",
    founded: 1974,
    national: false,
  },
  {
    id: 83,
    name: "FC Nantes",
    code: "NAN",
    country: "France",
    founded: 1943,
    national: false,
  },
  {
    id: 84,
    name: "OGC Nice",
    code: "NIC",
    country: "France",
    founded: 1904,
    national: false,
  },
  {
    id: 85,
    name: "Paris Saint-Germain",
    code: "PAR",
    country: "France",
    founded: 1970,
    national: false,
  },
  {
    id: 91,
    name: "AS Monaco",
    code: "MON",
    country: "France",
    founded: 1919,
    national: false,
  },
  {
    id: 93,
    name: "Stade DE Reims",
    code: "REI",
    country: "France",
    founded: 1909,
    national: false,
  },
  {
    id: 94,
    name: "Stade Rennais FC",
    code: "REN",
    country: "France",
    founded: 1901,
    national: false,
  },
  {
    id: 95,
    name: "RC Strasbourg Alsace",
    code: "STR",
    country: "France",
    founded: 1906,
    national: false,
  },
  {
    id: 96,
    name: "Toulouse FC",
    code: "TOU",
    country: "France",
    founded: 1937,
    national: false,
  },
  {
    id: 106,
    name: "Stade Brestois 29",
    code: "BRE",
    country: "France",
    founded: 1950,
    national: false,
  },
  {
    id: 108,
    name: "AJ Auxerre",
    code: "AUX",
    country: "France",
    founded: 1905,
    national: false,
  },
  {
    id: 111,
    name: "Havre Athletic Club",
    code: "HAV",
    country: "France",
    founded: 1872,
    national: false,
  },
  {
    id: 116,
    name: "RC Lens",
    code: "LEN",
    country: "France",
    founded: 1906,
    national: false,
  },
  {
    id: 1063,
    name: "AS Saint-Étienne",
    code: "ETI",
    country: "France",
    founded: 1920,
    national: false,
  },
];
