// "https://media.api-sports.io/football/teams/33.png"
export const Teams = [
  {
    id: 33,
    name: "Man Utd",
    code: "MUN",
    country: "England",
    founded: 1878,
    national: false,
  },
  {
    id: 34,
    name: "Newcastle",
    code: "NEW",
    country: "England",
    founded: 1892,
    national: false,
  },
  {
    id: 35,
    name: "Bournemouth",
    code: "BOU",
    country: "England",
    founded: 1899,
    national: false,
  },
  {
    id: 36,
    name: "Fulham",
    code: "FUL",
    country: "England",
    founded: 1879,
    national: false,
  },
  {
    id: 39,
    name: "Wolves",
    code: "WOL",
    country: "England",
    founded: 1877,
    national: false,
  },
  {
    id: 40,
    name: "Liverpool",
    code: "LIV",
    country: "England",
    founded: 1892,
    national: false,
  },
  {
    id: 41,
    name: "Southampton",
    code: "SOU",
    country: "England",
    founded: 1885,
    national: false,
  },
  {
    id: 42,
    name: "Arsenal",
    code: "ARS",
    country: "England",
    founded: 1886,
    national: false,
  },
  {
    id: 45,
    name: "Everton",
    code: "EVE",
    country: "England",
    founded: 1878,
    national: false,
  },
  {
    id: 46,
    name: "Leicester",
    code: "LEI",
    country: "England",
    founded: 1884,
    national: false,
  },
  {
    id: 47,
    name: "Spurs",
    code: "TOT",
    country: "England",
    founded: 1882,
    national: false,
  },
  {
    id: 48,
    name: "West Ham",
    code: "WES",
    country: "England",
    founded: 1895,
    national: false,
  },
  {
    id: 49,
    name: "Chelsea",
    code: "CHE",
    country: "England",
    founded: 1905,
    national: false,
  },
  {
    id: 50,
    name: "Man City",
    code: "MAC",
    country: "England",
    founded: 1880,
    national: false,
  },
  {
    id: 51,
    name: "Brighton",
    code: "BRI",
    country: "England",
    founded: 1901,
    national: false,
  },
  {
    id: 52,
    name: "Crystal Palace",
    code: "CRY",
    country: "England",
    founded: 1905,
    national: false,
  },
  {
    id: 55,
    name: "Brentford",
    code: "BRE",
    country: "England",
    founded: 1889,
    national: false,
  },
  {
    id: 57,
    name: "Ipswich",
    code: "IPS",
    country: "England",
    founded: 1878,
    national: false,
  },
  {
    id: 65,
    name: "Nott\u0027m Forest",
    code: "NOT",
    country: "England",
    founded: 1865,
    national: false,
  },
  {
    id: 66,
    name: "Aston Villa",
    code: "AST",
    country: "England",
    founded: 1874,
    national: false,
  },
];
