// "https://media.api-sports.io/football/teams/33.png"
export const Teams = [
  {
    id: 33,
    name: "Man Utd",
    code: "MUN",
    country: "England",
    founded: 1878,
    national: false,
  },
  {
    id: 34,
    name: "Newcastle",
    code: "NEW",
    country: "England",
    founded: 1892,
    national: false,
  },
  {
    id: 35,
    name: "Bournemouth",
    code: "BOU",
    country: "England",
    founded: 1899,
    national: false,
  },
  {
    id: 36,
    name: "Fulham",
    code: "FUL",
    country: "England",
    founded: 1879,
    national: false,
  },
  {
    id: 39,
    name: "Wolves",
    code: "WOL",
    country: "England",
    founded: 1877,
    national: false,
  },
  {
    id: 40,
    name: "Liverpool",
    code: "LIV",
    country: "England",
    founded: 1892,
    national: false,
  },
  {
    id: 41,
    name: "Southampton",
    code: "SOU",
    country: "England",
    founded: 1885,
    national: false,
  },
  {
    id: 42,
    name: "Arsenal",
    code: "ARS",
    country: "England",
    founded: 1886,
    national: false,
  },
  {
    id: 45,
    name: "Everton",
    code: "EVE",
    country: "England",
    founded: 1878,
    national: false,
  },
  {
    id: 46,
    name: "Leicester",
    code: "LEI",
    country: "England",
    founded: 1884,
    national: false,
  },
  {
    id: 47,
    name: "Spurs",
    code: "TOT",
    country: "England",
    founded: 1882,
    national: false,
  },
  {
    id: 48,
    name: "West Ham",
    code: "WES",
    country: "England",
    founded: 1895,
    national: false,
  },
  {
    id: 49,
    name: "Chelsea",
    code: "CHE",
    country: "England",
    founded: 1905,
    national: false,
  },
  {
    id: 50,
    name: "Man City",
    code: "MAC",
    country: "England",
    founded: 1880,
    national: false,
  },
  {
    id: 51,
    name: "Brighton",
    code: "BRI",
    country: "England",
    founded: 1901,
    national: false,
  },
  {
    id: 52,
    name: "Crystal Palace",
    code: "CRY",
    country: "England",
    founded: 1905,
    national: false,
  },
  {
    id: 55,
    name: "Brentford",
    code: "BRE",
    country: "England",
    founded: 1889,
    national: false,
  },
  {
    id: 57,
    name: "Ipswich",
    code: "IPS",
    country: "England",
    founded: 1878,
    national: false,
  },
  {
    id: 65,
    name: "Nott\u0027m Forest",
    code: "NOT",
    country: "England",
    founded: 1865,
    national: false,
  },
  {
    id: 66,
    name: "Aston Villa",
    code: "AST",
    country: "England",
    founded: 1874,
    national: false,
  },
  // LALIGA

  {
    id: 529,
    name: "FC Barcelona",
    code: "BAR",
    country: "Spain",
    founded: 1899,
    national: false,
  },
  {
    id: 530,
    name: "Atlético de Madrid",
    code: "MAD",
    country: "Spain",
    founded: 1903,
    national: false,
  },
  {
    id: 531,
    name: "Athletic Club",
    code: "BIL",
    country: "Spain",
    founded: 1898,
    national: false,
  },
  {
    id: 532,
    name: "Valencia CF",
    code: "VAL",
    country: "Spain",
    founded: 1919,
    national: false,
  },
  {
    id: 533,
    name: "Villarreal CF",
    code: "VIL",
    country: "Spain",
    founded: 1923,
    national: false,
  },
  {
    id: 534,
    name: "UD Las Palmas",
    code: "PAL",
    country: "Spain",
    founded: 1949,
    national: false,
  },
  {
    id: 536,
    name: "Sevilla FC",
    code: "SEV",
    country: "Spain",
    founded: 1890,
    national: false,
  },
  {
    id: 537,
    name: "CD Leganés",
    code: "LEG",
    country: "Spain",
    founded: 1928,
    national: false,
  },
  {
    id: 538,
    name: "RC Celta",
    code: "CEL",
    country: "Spain",
    founded: 1923,
    national: false,
  },
  {
    id: 540,
    name: "RCD Espanyol de Barcelona",
    code: "ESP",
    country: "Spain",
    founded: 1900,
    national: false,
  },
  {
    id: 541,
    name: "Real Madrid",
    code: "REA",
    country: "Spain",
    founded: 1902,
    national: false,
  },
  {
    id: 542,
    name: "Deportivo Alavés",
    code: "ALA",
    country: "Spain",
    founded: 1921,
    national: false,
  },
  {
    id: 543,
    name: "Real Betis",
    code: "BET",
    country: "Spain",
    founded: 1907,
    national: false,
  },
  {
    id: 546,
    name: "Getafe CF",
    code: "GET",
    country: "Spain",
    founded: 1983,
    national: false,
  },
  {
    id: 547,
    name: "Girona FC",
    code: "GIR",
    country: "Spain",
    founded: 1930,
    national: false,
  },
  {
    id: 548,
    name: "Real Sociedad",
    code: "RSO",
    country: "Spain",
    founded: 1909,
    national: false,
  },
  {
    id: 720,
    name: "Real Valladolid CF",
    code: "VAL",
    country: "Spain",
    founded: 1928,
    national: false,
  },
  {
    id: 727,
    name: "CA Osasuna",
    code: "OSA",
    country: "Spain",
    founded: 1920,
    national: false,
  },
  {
    id: 728,
    name: "Rayo Vallecano",
    code: "RAY",
    country: "Spain",
    founded: 1924,
    national: false,
  },
  {
    id: 798,
    name: "RCD Mallorca",
    code: "MAL",
    country: "Spain",
    founded: 1916,
    national: false,
  },
];
